[project]
name = "babylon-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiosqlite>=0.21.0",
    "fastapi>=0.116.1",
    "ollama>=0.5.3",
    "pydantic-settings>=2.10.1",
    "uvicorn>=0.35.0",
]
